DOCUMENT=thesis
#OPEN=acroread
OPEN=evince

#all: check paper open
all: check paper

open:
	$(OPEN) $(DOCUMENT).pdf &
	cp $(DOCUMENT).pdf ~/PublicWebPages/fktmp/

check:
	./spellcheck.sh

paper:
	latex $(DOCUMENT).tex
	bibtex $(DOCUMENT)
	latex $(DOCUMENT).tex
	latex $(DOCUMENT).tex
	dvipdfm -p a4 -o $(DOCUMENT).pdf $(DOCUMENT).dvi

clean:
	rm -f *.bbl *.blg *.log *.aux *.toc *~
